import type { Metadata } from "next";
import { DynaPuff } from "next/font/google";
import "./globals.css";
import HeaderClientWrapper from "@/components/HeaderClientWrapper";
import Footer from "@/components/Footer";

const dynaPuff = DynaPuff({
  variable: "--font-dyna-puff",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${dynaPuff.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <HeaderClientWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}
